# Generated by Django 3.1.2 on 2020-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduser',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
