# Generated by Django 3.1.2 on 2020-12-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201206_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaileduser',
            name='dist',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
