# Generated by Django 3.1.4 on 2020-12-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('bloodgroup', models.CharField(max_length=30)),
                ('preference', models.CharField(max_length=30)),
                ('recent', models.CharField(max_length=30)),
                ('frequent', models.CharField(max_length=30)),
                ('monetary', models.CharField(max_length=30)),
                ('times', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
    ]
